const studentSeed = [
	{
		firstName: "Cody",
		lastName: "Chan",
		email: "cody.chan@gmail.com",
		imageUrl:
			"https://target.scene7.com/is/image/Target/GUEST_3d2a8073-36e6-4cec-8c8c-872639105820?wid=488&hei=488&fmt=pjpeg",
		campusId: 1,
		gpa: 2.1,
	},
	{
		firstName: "Mason",
		lastName: "Chan",
		email: "Mason.chan@gmail.com",
		campusId: 2,
		gpa: 0,
	},
	{
		firstName: "Winnie",
		lastName: "Lau",
		email: "winnie.lau@gmail.com",
		campusId: 1,
		gpa: 3.9,
	},
	{
		firstName: "Zach",
		lastName: "Byerly",
		email: "Zach.Byerly@gmail.com",
		campusId: 3,
	},
];
const campusSeed = [
	{
		name: "Acme Elementary",
		address: "300 park pl, New York, NY",
		description:
			"Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatem, exercitationem provident quasi, placeat hic impedit vel qui iusto voluptas, distinctio cupiditate iure sed rerum repellendus veritatis eveniet! Autem, officiis ipsum.",
	},
	{
		name: "Acme Middle",
		address: "330 park pl, New York, NY",
		description:
			"Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iure quam aliquam consequuntur eveniet, modi neque totam illum? Est nam ut ipsum modi laudantium blanditiis, sapiente nobis animi, temporibus ex soluta?",
	},
	{
		name: "Acme High",
		address: "360 park pl, New York, NY",
		description:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis quibusdam asperiores numquam placeat, facilis veniam, aliquam natus ipsa quidem pariatur est doloribus et nostrum reprehenderit ea! Accusantium fugit fugiat consectetur?",
	},
];
const studentSeed2 = [
	{
		firstName: "Miner",
		lastName: "Frantz",
		email: "mfrantz0@discovery.com",
		campusId: 1,
	},
	{
		firstName: "Morton",
		lastName: "Ameer-Beg",
		email: "mameerbeg1@microsoft.com",
		campusId: 3,
	},
	{
		firstName: "Stillmann",
		lastName: "Mount",
		email: "smount2@slate.com",
		campusId: 2,
	},
	{
		firstName: "Floris",
		lastName: "Collumbell",
		email: "fcollumbell3@sfgate.com",
		campusId: 1,
	},
	{
		firstName: "Chev",
		lastName: "Mulvenna",
		email: "cmulvenna4@mysql.com",
		campusId: 3,
	},
	{
		firstName: "Karyn",
		lastName: "Bullivant",
		email: "kbullivant5@vkontakte.ru",
		campusId: 2,
	},
	{
		firstName: "Mickey",
		lastName: "Mathely",
		email: "mmathely6@google.it",
		campusId: 1,
	},
	{
		firstName: "Jeannie",
		lastName: "Carrivick",
		email: "jcarrivick7@omniture.com",
		campusId: 2,
	},
	{
		firstName: "Babbette",
		lastName: "Goane",
		email: "bgoane8@china.com.cn",
		campusId: 3,
	},
	{
		firstName: "Herc",
		lastName: "Jennemann",
		email: "hjennemann9@cbsnews.com",
		campusId: 3,
	},
	{
		firstName: "Geri",
		lastName: "Crighton",
		email: "gcrightona@va.gov",
		campusId: 3,
	},
	{
		firstName: "Cozmo",
		lastName: "Amar",
		email: "camarb@1688.com",
		campusId: 1,
	},
	{
		firstName: "Melesa",
		lastName: "Trassler",
		email: "mtrasslerc@google.co.jp",
		campusId: 1,
	},
	{
		firstName: "Madge",
		lastName: "Steutly",
		email: "msteutlyd@unc.edu",
		campusId: 1,
	},
	{
		firstName: "Burch",
		lastName: "Schachter",
		email: "bschachtere@fc2.com",
		campusId: 3,
	},
	{
		firstName: "Adriano",
		lastName: "Mingo",
		email: "amingof@acquirethisname.com",
		campusId: 3,
	},
	{
		firstName: "Emlyn",
		lastName: "Scoines",
		email: "escoinesg@csmonitor.com",
		campusId: 1,
	},
	{
		firstName: "Guendolen",
		lastName: "Glasgow",
		email: "gglasgowh@livejournal.com",
		campusId: 1,
	},
	{
		firstName: "Gay",
		lastName: "Boxell",
		email: "gboxelli@instagram.com",
		campusId: 2,
	},
	{
		firstName: "Olimpia",
		lastName: "Caine",
		email: "ocainej@latimes.com",
		campusId: 2,
	},
	{
		firstName: "Stanislaus",
		lastName: "Hugues",
		email: "shuguesk@odnoklassniki.ru",
		campusId: 2,
	},
	{
		firstName: "Dunstan",
		lastName: "Scraney",
		email: "dscraneyl@thetimes.co.uk",
		campusId: 2,
	},
	{
		firstName: "Lorrie",
		lastName: "Addionizio",
		email: "laddioniziom@ehow.com",
		campusId: 1,
	},
	{
		firstName: "Blaire",
		lastName: "Foxen",
		email: "bfoxenn@imdb.com",
		campusId: 3,
	},
	{
		firstName: "Annelise",
		lastName: "Wickliffe",
		email: "awickliffeo@oakley.com",
		campusId: 3,
	},
	{
		firstName: "Myca",
		lastName: "Martschke",
		email: "mmartschkep@auda.org.au",
		campusId: 1,
	},
	{
		firstName: "Oberon",
		lastName: "Give",
		email: "ogiveq@businesswire.com",
		campusId: 1,
	},
	{
		firstName: "Pepito",
		lastName: "Pinson",
		email: "ppinsonr@nps.gov",
		campusId: 1,
	},
	{
		firstName: "Dov",
		lastName: "Noury",
		email: "dnourys@telegraph.co.uk",
		campusId: 3,
	},
	{
		firstName: "Jake",
		lastName: "Chaplyn",
		email: "jchaplynt@nih.gov",
		campusId: 1,
	},
	{
		firstName: "Mavra",
		lastName: "Bourdas",
		email: "mbourdasu@ocn.ne.jp",
		campusId: 2,
	},
	{
		firstName: "Dominik",
		lastName: "Mulqueen",
		email: "dmulqueenv@seattletimes.com",
		campusId: 1,
	},
	{
		firstName: "Jaquenetta",
		lastName: "Livezley",
		email: "jlivezleyw@adobe.com",
		campusId: 2,
	},
	{
		firstName: "Zebadiah",
		lastName: "Nannoni",
		email: "znannonix@hud.gov",
		campusId: 1,
	},
	{
		firstName: "Kaycee",
		lastName: "Lembke",
		email: "klembkey@etsy.com",
		campusId: 3,
	},
	{
		firstName: "Zelda",
		lastName: "Syrad",
		email: "zsyradz@tumblr.com",
		campusId: 1,
	},
	{
		firstName: "Sher",
		lastName: "Lambrick",
		email: "slambrick10@altervista.org",
		campusId: 3,
	},
	{
		firstName: "Wallis",
		lastName: "Metterick",
		email: "wmetterick11@archive.org",
		campusId: 1,
	},
	{
		firstName: "Ronda",
		lastName: "Figurski",
		email: "rfigurski12@list-manage.com",
		campusId: 2,
	},
	{
		firstName: "Sebastian",
		lastName: "Dewan",
		email: "sdewan13@ifeng.com",
		campusId: 2,
	},
	{
		firstName: "Alina",
		lastName: "McMorland",
		email: "amcmorland14@sphinn.com",
		campusId: 2,
	},
	{
		firstName: "Suellen",
		lastName: "Ledgeway",
		email: "sledgeway15@clickbank.net",
		campusId: 1,
	},
	{
		firstName: "Fawn",
		lastName: "Seabourne",
		email: "fseabourne16@is.gd",
		campusId: 3,
	},
	{
		firstName: "Pier",
		lastName: "Costanza",
		email: "pcostanza17@google.co.uk",
		campusId: 2,
	},
	{
		firstName: "Stephanus",
		lastName: "Corse",
		email: "scorse18@prnewswire.com",
		campusId: 2,
	},
	{
		firstName: "Amerigo",
		lastName: "O'Currigan",
		email: "aocurrigan19@statcounter.com",
		campusId: 3,
	},
	{
		firstName: "Ninetta",
		lastName: "Mudie",
		email: "nmudie1a@gnu.org",
		campusId: 3,
	},
	{
		firstName: "Say",
		lastName: "Giorgielli",
		email: "sgiorgielli1b@soup.io",
		campusId: 2,
	},
	{
		firstName: "Alameda",
		lastName: "Daverin",
		email: "adaverin1c@ihg.com",
		campusId: 3,
	},
	{
		firstName: "Loria",
		lastName: "Hupe",
		email: "lhupe1d@cbsnews.com",
		campusId: 2,
	},
	{
		firstName: "Sherlock",
		lastName: "Pattrick",
		email: "spattrick1e@yandex.ru",
		campusId: 2,
	},
	{
		firstName: "Huntington",
		lastName: "Guildford",
		email: "hguildford1f@pbs.org",
		campusId: 2,
	},
	{
		firstName: "Raquel",
		lastName: "Veldens",
		email: "rveldens1g@stumbleupon.com",
		campusId: 1,
	},
	{
		firstName: "Jabez",
		lastName: "Cleve",
		email: "jcleve1h@sciencedaily.com",
		campusId: 1,
	},
	{
		firstName: "Vonni",
		lastName: "Baine",
		email: "vbaine1i@squidoo.com",
		campusId: 3,
	},
	{
		firstName: "Bartram",
		lastName: "Vila",
		email: "bvila1j@webeden.co.uk",
		campusId: 1,
	},
	{
		firstName: "Bud",
		lastName: "Anderbrugge",
		email: "banderbrugge1k@ucsd.edu",
		campusId: 1,
	},
	{
		firstName: "Marcello",
		lastName: "Derbyshire",
		email: "mderbyshire1l@usnews.com",
		campusId: 1,
	},
	{
		firstName: "Carri",
		lastName: "Bleas",
		email: "cbleas1m@usgs.gov",
		campusId: 2,
	},
	{
		firstName: "Reagen",
		lastName: "Bruins",
		email: "rbruins1n@msu.edu",
		campusId: 2,
	},
	{
		firstName: "Renelle",
		lastName: "Krzysztof",
		email: "rkrzysztof1o@etsy.com",
		campusId: 2,
	},
	{
		firstName: "Xever",
		lastName: "Stratz",
		email: "xstratz1p@yahoo.com",
		campusId: 1,
	},
	{
		firstName: "Daniele",
		lastName: "Kaplin",
		email: "dkaplin1q@paginegialle.it",
		campusId: 1,
	},
	{
		firstName: "Zonnya",
		lastName: "Worts",
		email: "zworts1r@sciencedirect.com",
		campusId: 1,
	},
	{
		firstName: "Harriott",
		lastName: "Worge",
		email: "hworge1s@360.cn",
		campusId: 2,
	},
	{
		firstName: "Jerome",
		lastName: "Dauber",
		email: "jdauber1t@weibo.com",
		campusId: 1,
	},
	{
		firstName: "Hurleigh",
		lastName: "Lorant",
		email: "hlorant1u@addtoany.com",
		campusId: 2,
	},
	{
		firstName: "Dagny",
		lastName: "Middiff",
		email: "dmiddiff1v@amazon.co.uk",
		campusId: 2,
	},
	{
		firstName: "Cyrill",
		lastName: "Scrammage",
		email: "cscrammage1w@whitehouse.gov",
		campusId: 1,
	},
	{
		firstName: "Katrine",
		lastName: "Winspare",
		email: "kwinspare1x@toplist.cz",
		campusId: 1,
	},
	{
		firstName: "Archaimbaud",
		lastName: "Earingey",
		email: "aearingey1y@hugedomains.com",
		campusId: 3,
	},
	{
		firstName: "Cart",
		lastName: "Floodgate",
		email: "cfloodgate1z@t.co",
		campusId: 3,
	},
	{
		firstName: "Milka",
		lastName: "MacCaughan",
		email: "mmaccaughan20@eepurl.com",
		campusId: 1,
	},
	{
		firstName: "Myrle",
		lastName: "Essam",
		email: "messam21@phoca.cz",
		campusId: 3,
	},
	{
		firstName: "Dag",
		lastName: "Coupman",
		email: "dcoupman22@ask.com",
		campusId: 2,
	},
	{
		firstName: "Gav",
		lastName: "Tampen",
		email: "gtampen23@illinois.edu",
		campusId: 3,
	},
	{
		firstName: "Chicky",
		lastName: "Greenstead",
		email: "cgreenstead24@irs.gov",
		campusId: 2,
	},
	{
		firstName: "Marnie",
		lastName: "Neicho",
		email: "mneicho25@yale.edu",
		campusId: 3,
	},
	{
		firstName: "Jazmin",
		lastName: "Guillerman",
		email: "jguillerman26@answers.com",
		campusId: 3,
	},
	{
		firstName: "Tedra",
		lastName: "Dumbreck",
		email: "tdumbreck27@about.me",
		campusId: 1,
	},
	{
		firstName: "Shelbi",
		lastName: "Berrygun",
		email: "sberrygun28@baidu.com",
		campusId: 1,
	},
	{
		firstName: "Justinn",
		lastName: "Lys",
		email: "jlys29@dropbox.com",
		campusId: 1,
	},
	{
		firstName: "Vassily",
		lastName: "Dwight",
		email: "vdwight2a@pagesperso-orange.fr",
		campusId: 1,
	},
	{
		firstName: "Emily",
		lastName: "Gavahan",
		email: "egavahan2b@ibm.com",
		campusId: 2,
	},
	{
		firstName: "Yasmin",
		lastName: "Westwick",
		email: "ywestwick2c@shareasale.com",
		campusId: 2,
	},
	{
		firstName: "Emery",
		lastName: "Breedy",
		email: "ebreedy2d@stanford.edu",
		campusId: 1,
	},
	{
		firstName: "Vivia",
		lastName: "Stuckey",
		email: "vstuckey2e@google.com.br",
		campusId: 3,
	},
	{
		firstName: "Hall",
		lastName: "Wanklyn",
		email: "hwanklyn2f@amazonaws.com",
		campusId: 3,
	},
	{
		firstName: "Conway",
		lastName: "Batchelor",
		email: "cbatchelor2g@a8.net",
		campusId: 1,
	},
	{
		firstName: "Sharona",
		lastName: "Sabbins",
		email: "ssabbins2h@youtu.be",
		campusId: 3,
	},
	{
		firstName: "Abie",
		lastName: "Deller",
		email: "adeller2i@usa.gov",
		campusId: 3,
	},
	{
		firstName: "Danya",
		lastName: "Pouck",
		email: "dpouck2j@netlog.com",
		campusId: 1,
	},
	{
		firstName: "Dru",
		lastName: "Dulany",
		email: "ddulany2k@dell.com",
		campusId: 2,
	},
	{
		firstName: "Gaby",
		lastName: "Melmeth",
		email: "gmelmeth2l@technorati.com",
		campusId: 1,
	},
	{
		firstName: "Umeko",
		lastName: "McCaughen",
		email: "umccaughen2m@phoca.cz",
		campusId: 1,
	},
	{
		firstName: "Ginelle",
		lastName: "Imrie",
		email: "gimrie2n@ifeng.com",
		campusId: 2,
	},
	{
		firstName: "Ingemar",
		lastName: "Charon",
		email: "icharon2o@nps.gov",
		campusId: 1,
	},
	{
		firstName: "Hillary",
		lastName: "McGenn",
		email: "hmcgenn2p@sitemeter.com",
		campusId: 1,
	},
	{
		firstName: "Jandy",
		lastName: "Spruce",
		email: "jspruce2q@usnews.com",
		campusId: 3,
	},
	{
		firstName: "Arlen",
		lastName: "Smalcombe",
		email: "asmalcombe2r@fotki.com",
		campusId: 1,
	},
];
module.exports = { studentSeed, campusSeed, studentSeed2 };
